name: Dana
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^1.0.0
  # code_field: ^1.22.0
  firebase_auth: ^3.3.4
  firebase_database: ^9.0.4
  firebase_core: ^1.10.6
  firebase_storage: ^10.2.4
  firebase_dynamic_links: ^4.0.3
  firebase_analytics: ^9.0.4
  firebase_messaging: ^11.2.4
  cloud_firestore: ^3.1.5
  shared_preferences: ^2.0.11
  provider: ^5.0.0
  another_flushbar: ^1.10.28
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.4+4
  permission_handler: ^8.3.0
  animator: ^3.1.0
  cached_network_image: ^3.2.0
  # camera: ^0.9.2
  camera: ^0.9.4+5
  flutter_image_compress: ^1.1.0
  giphy_get: ^2.0.2
  http: ^0.13.4
  intl: ^0.17.0
  ionicons: ^0.1.2
  path_provider: ^2.0.8
  share: ^2.0.4
  timeago: ^3.1.0
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  gallery_saver: ^2.3.2
  file_picker: ^4.3.0
  agora_rtc_engine: ^4.0.7
  # flutter_plugin_record: ^1.0.1
  # flutter_sound: ^8.3.9
  record: ^3.0.2
  auto_direction: ^0.0.5
  liquid_swipe: ^2.1.0
  audioplayers: ^0.20.1
  video_player: ^2.2.10
  chewie: ^1.2.2
  images_picker: ^1.2.10
  mime: ^1.0.1
  open_file: ^3.2.1
  switcher_button: ^0.0.4
  flutter_datetime_picker: ^1.5.1
  # collection: ^1.15.0
  connectivity_plus: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  syncfusion_flutter_pdfviewer: ^19.4.41-beta
  # syncfusion_flutter_pdfviewer_web: ^19.3.46-beta
  flutter_local_notifications: ^9.2.0
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  linkable: ^3.0.1
  linkwell: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

flutter_icons:
  # android: "launcher_icon"
  ios: true
  image_path: "assets/images/dan.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf

    - family: Poppins-Italic
      fonts:
        - asset: assets/fonts/Poppins-Italic.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
